---
ilike: 
  version: 0.0.1
  required: false
  requirements: 
    liberty: 
      min: 2.1.7
  description: >
    A very simple search engine. Only makes sense on small sites since it searches the database directly without any abstraction layer.
  license: 
    name: LGPL
    description: Licensed under the GNU LESSER GENERAL PUBLIC LICENSE.
    url: http://www.gnu.org/copyleft/lesser.html 
  homeable: false
  permissions: 
    p_ilike_search: 
      description: >
        Can search your site using the search
        engine
      level: basic
  plugins:
    ilike_search:
      handler_file: iLike.php
      api_handlers:
        sql:
          content_list_sql: ilike_content_list_sql
        tpl:
          content_search: 'bitpackage:ilike/search_inc.tpl'
